* Introduction
   you are asserting that this asymptotic analysis tells us something about overfit.
   - why?
** Spell out the object the paper studies
** Motivation for studying that object
*** Want to improve on approximations for the finite sample dist of out-of-sample stats for evaluating forecast performance
**** Fitting too many parameters makes asymptotic results misleading
    i.e. we are more comfortable using standard confidence intervals when we have 100 observations
    and calculate the sample mean, than we would be if we regressed the same variable on 30 predictors.
***** How to study this systematically?
****** let k and T both increase, k = O(T^p)
****** gives some guidance for which pairs of k and T are likely to be problematic in practice
****** if we knew asymp. normality holds for k/T -> 0.3, then we should be as comfortable doing a regression on 30 predictors as on 1, if n = 100.
***** need k/T -> 0
****** gives consistency and normality (Huber (1973))
**** Hasn't been shown that out-of-sample stats work
**** out-of-sample stats are often used _because_ the researcher expects in-sample stats to be misleading
*** Want to understand whether one should do in-sample or out-of-sample forecast evaluation
** Conclusions
*** true relationships
**** out-of-sample and in-sample do the same thing  
***** k/T -> 0 means they both work
***** k/T -> positive const. means they both fail 
*** Inference about forecast performance
   i.e. what you should expect to happen if you make forecasts for period T+1
**** out-of-sample analysis tells you how the period R estimated model will do in period T+1
***** sort of obvious intuitively
***** tricky to show with dependent data
***** true for any estimated coefficients
**** we give conditions where this converges the period T+1 performance of the full-sample model
***** implicit change of measure
**** What does performance depend on?
***** Depends on sample size
      with just 30 observations, you don't want to fit a VAR
***** Depends on luck
      Sometimes you will be using a model that does well on average, but the particular dataset
      gives bad coefficient estimates
***** Might depend on other observable information
* Lit. Review
  - want to show why F-test, etc break down
  - want to show why west, clark and mccracken et al break down
  - want to show why giacomini and white's approach really doesn't work well
** compare west to in-sample
*** one model